GET https://localhost:7020/companies
Accept: application/json

###

GET https://localhost:7020/companies/1
Accept: application/json

###

GET https://localhost:7020/companies/-1
Accept: application/json

###

GET https://localhost:7020/companies/1/employees/E164342
Accept: application/json

###

GET https://localhost:7020/companies/5/employees/E196582
Accept: application/json

###